config/routes.rb
# frozen_string_literal: true
Rails.application.routes.draw do
  root 'appointment_summaries#new'

  resources :appointment_summaries, only: %i(new create) do
    post :preview, on: :collection
  end

  scope path: 'styleguide', controller: 'styleguide' do
    scope path: 'pages' do
      get 'input', action: 'pages_input'
      get 'output-base', action: 'pages_output_base'
      get 'output-50-54', action: 'pages_output_50_54'
      get 'output-base-large', action: 'pages_output_base_large'
      get 'output-50-54-large', action: 'pages_output_50_54_large'
      get 'output-ineligible', action: 'pages_output_ineligible'
    end

    get '/', action: :index
  end

  get '/status', to: 'status#show'

  namespace :admin do
    resources :appointment_summaries, only: :index
  end

  mount GovukAdminTemplate::Engine, at: '/style-guide'
end

app/models/appointment_summary.rb
# frozen_string_literal: true
class AppointmentSummary < ActiveRecord::Base
  deprecated_columns :income_in_retirement

  TITLES = %w(Mr Mrs Miss Ms Mx Dr Reverend).freeze

  belongs_to :user

  validates :title, presence: true, inclusion: { in: TITLES, allow_blank: true }
  validates :last_name, presence: true
  validates :date_of_appointment, timeliness: { on_or_before: -> { Time.zone.today },
                                                on_or_after: Date.new(2015),
                                                type: :date }

  validates :guider_name, presence: true
  validates :address_line_1, presence: true
  validates :town, presence: true
  validates :postcode, presence: true
  validates :country, presence: true, inclusion: { in: Countries.all }

  validates :has_defined_contribution_pension,
            presence: true,
            inclusion: {
              in: %w(yes no unknown),
              allow_blank: true,
              message: '%{value} is not a valid value'
            }
  validates :pension_pot_accuracy, presence: true, unless: ->(as) { as.has_defined_contribution_pension == 'no' }

  validates :format_preference, inclusion: { in: %w(standard large_text) }
  validates :appointment_type, inclusion: { in: %w(standard 50_54) }
  validates :number_of_previous_appointments, inclusion: { in: 0..3 }

  def eligible_for_guidance?
    %w(yes unknown).include?(has_defined_contribution_pension)
  end

  def self.editable_column_names
    column_names - %w(id created_at updated_at user_id guider_organisation)
  end
end

app/controllers/admin/appointment_summaries_controller.rb
# frozen_string_literal: true
module Admin
  class AppointmentSummariesController < ::ApplicationController
    before_action :authenticate_admin!

    def index
      @appointment_form = AppointmentSummaryBrowser.new(form_params)

      respond_to do |format|
        format.html
        format.csv { render csv: AppointmentSummaryCsv.new(@appointment_form.results) }
      end
    end

    private

    def form_params
      {
        page:       params[:page],
        start_date: params.dig(:appointment_summary_browser, :start_date),
        end_date:   params.dig(:appointment_summary_browser, :end_date)
      }
    end

    def authenticate_admin!
      authorise_user!('analyst')
    rescue PermissionDeniedException
      redirect_to :root
    end
  end
end

app/controllers/appointment_summaries_controller.rb
# frozen_string_literal: true
class AppointmentSummariesController < ApplicationController
  def new
    @appointment_summary = AppointmentSummary.new(date_of_appointment: Time.zone.today)
  end

  def create
    appointment_summary = AppointmentSummary.create!(appointment_summary_params)
    output_document = OutputDocument.new(appointment_summary)

    respond_to do |format|
      format.html { render html: output_document.html.html_safe } # rubocop: disable OutputSafety
      format.pdf do
        send_data output_document.pdf,
                  filename: 'pension_wise.pdf', type: 'application/pdf',
                  disposition: :inline
      end
    end
  end

  def preview
    @appointment_summary = AppointmentSummary.new(appointment_summary_params)
    if @appointment_summary.valid?
      @output_document = OutputDocument.new(@appointment_summary)
    else
      render :new
    end
  end

  private

  def appointment_summary_params
    params
      .require(:appointment_summary)
      .permit(*AppointmentSummary.editable_column_names)
      .merge(user: current_user)
  end
end

app/views/admin/appointment_summaries/index.html.erb
<h1><%= title 'Appointment Summaries' %></h1>

<div class="well">
  <%= form_for @appointment_form, url: admin_appointment_summaries_path, method: :get, html: { class: 'inline form-inline' } do |f| %>
    <div class="form-group">
      <%= f.label :start_date, 'From', class: 'inline' %>
      <%= f.text_field :start_date, class: 'form-control t-start', placeholder: 'dd/mm/yyyy' %>
    </div>
    <div class="form-group">
      <%= f.label :end_date, 'To', class: 'inline' %>
      <%= f.text_field :end_date, class: 'form-control t-end', placeholder: 'dd/mm/yyyy' %>
    </div>
    <%= f.submit 'Search', class: 'btn btn-default' %>
  <% end %>

  <%= form_for @appointment_form, url: admin_appointment_summaries_path(format: :csv), method: :get, html: { class: 'inline form-inline' } do |f| %>
    <%= f.hidden_field :start_date %>
    <%= f.hidden_field :end_date %>
    <%= f.submit 'Export CSV', class: 'btn btn-default t-export' %>
  <% end %>
</div>

<%= paginate @appointment_form.paginated_results, theme: 'twitter-bootstrap-3' %>

<table class="table table-striped table-bordered">
  <thead>
    <tr class="table-header">
      <th scope="col">Organisation</th>
      <th scope="col">Reference</th>
      <th scope="col">Guider</th>
      <th scope="col">Customer</th>
      <th scope="col">Appointment Date</th>
    </tr>
  </thead>
  <tbody>
    <% @appointment_form.paginated_results.each do |summary| %>
      <tr class="t-appointment">
        <td><%= summary.user.organisation_slug.upcase %></td>
        <td><%= summary.reference_number %></td>
        <td><%= summary.guider_name %></td>
        <td><%= "#{summary.title} #{summary.first_name} #{summary.last_name}" %></td>
        <td><%= summary.date_of_appointment.to_s(:gov_uk) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @appointment_form.paginated_results, theme: 'twitter-bootstrap-3' %>